### ISSUE TITLE
TODO task list

### ISSUE THREAD

**Issue by ygongdev** [ygongdev/maplestory-flag-race-simulator#1]
# Living task list

## 1. Finish drawing tilemap layers
- [ ] slope layer
- [ ] foundation layer
- [ ] pass-through-platform layer (you can jump through platforms except, but has to collide at top of platform, so you don't fall)
- [ ] rope layer
- [ ] booster portal layer
- [ ] teleport portal layer
- [ ] stuck-in-pit-fly-up layer
- [ ] item layer (s jump, etc)
- [ ] fire layer

## 2. Implement pass-through platform layer collision mechanics
- [ ] allow player to go through platform when coming from the bottom
- [ ] Do not let player fall through platform when standing on top

## 3. Bugs
- [ ] Stop getting yeeted off slope when walking off slope
- [ ] Figure out the correct jump velocity
- [ ] Figure out the correct applied force for acceleration + damping

## 4. Features
- [ ] Track time 
- [ ] Track laps
- [ ] Artifically loading
- [ ] Start button 
- [ ] Flag race music
